import React, { useState, useEffect } from 'react';
import { Database, Search, Info } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import ToolPageWrapper from '@/components/tools/ToolPageWrapper';
import ResultCard from '@/components/tools/ResultCard';

// Common OUI database (subset - in production you'd have a larger database)
const ouiDatabase = {
  '00:00:0C': { vendor: 'Cisco Systems', type: 'Network Equipment' },
  '00:01:42': { vendor: 'Cisco Systems', type: 'Network Equipment' },
  '00:1A:A0': { vendor: 'Dell Technologies', type: 'Computer' },
  '00:14:22': { vendor: 'Dell Technologies', type: 'Computer' },
  '00:50:56': { vendor: 'VMware', type: 'Virtualization' },
  '00:0C:29': { vendor: 'VMware', type: 'Virtualization' },
  '00:15:5D': { vendor: 'Microsoft (Hyper-V)', type: 'Virtualization' },
  '00:1C:42': { vendor: 'Parallels', type: 'Virtualization' },
  '08:00:27': { vendor: 'Oracle VirtualBox', type: 'Virtualization' },
  '00:1A:11': { vendor: 'Google', type: 'Cloud/Data Center' },
  'AC:1F:6B': { vendor: 'Super Micro Computer', type: 'Server' },
  '00:25:90': { vendor: 'Super Micro Computer', type: 'Server' },
  'EC:F4:BB': { vendor: 'Hewlett Packard Enterprise', type: 'Server/Network' },
  '3C:D9:2B': { vendor: 'Hewlett Packard', type: 'Computer' },
  '00:17:A4': { vendor: 'Hewlett-Packard', type: 'Network' },
  'F0:92:1C': { vendor: 'Hewlett Packard', type: 'Computer' },
  '00:1E:68': { vendor: 'Quanta Computer', type: 'Server/ODM' },
  '00:1B:21': { vendor: 'Intel', type: 'Network Interface' },
  '00:1F:C6': { vendor: 'Intel', type: 'Network Interface' },
  '00:1E:67': { vendor: 'Intel', type: 'Network Interface' },
  '3C:FD:FE': { vendor: 'Intel', type: 'Network Interface' },
  '00:1A:2B': { vendor: 'Ayecom Technology', type: 'Network' },
  '00:0D:93': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:1B:63': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:0F:24': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:21:E9': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:60:B6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:1F:F3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:22:41': { vendor: 'Apple', type: 'Consumer Electronics' },
  '14:A5:1A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'FC:FC:48': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:17:F2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:1C:B3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:23:12': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:26:B0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:26:BB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '18:E7:F4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:26:96': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:8B:7F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:24:E8': { vendor: 'Dell', type: 'Computer' },
  '00:21:9B': { vendor: 'Dell', type: 'Computer' },
  '18:A9:9B': { vendor: 'Dell', type: 'Computer' },
  '00:1E:4F': { vendor: 'Dell', type: 'Computer' },
  'F8:DB:88': { vendor: 'Dell', type: 'Computer' },
  '00:1D:09': { vendor: 'Dell', type: 'Computer' },
  'B0:83:FE': { vendor: 'Dell', type: 'Computer' },
  '00:19:B9': { vendor: 'Dell', type: 'Computer' },
  '00:06:5B': { vendor: 'Dell', type: 'Computer' },
  '00:11:43': { vendor: 'Dell', type: 'Computer' },
  '00:12:3F': { vendor: 'Dell', type: 'Computer' },
  '00:15:C5': { vendor: 'Dell', type: 'Computer' },
  '00:18:8B': { vendor: 'Dell', type: 'Computer' },
  '34:17:EB': { vendor: 'Dell', type: 'Computer' },
  '90:B1:1C': { vendor: 'Dell', type: 'Computer' },
  '78:45:C4': { vendor: 'Dell', type: 'Computer' },
  '00:04:5A': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:0C:41': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:12:17': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:13:10': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:14:BF': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:16:B6': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:18:39': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1A:70': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1C:10': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1D:7E': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1E:E5': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:22:6B': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:23:69': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:25:9C': { vendor: 'Linksys', type: 'Consumer Network' },
  '68:7F:74': { vendor: 'Linksys', type: 'Consumer Network' },
  'C0:C1:C0': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1D:0F': { vendor: 'TP-Link', type: 'Consumer Network' },
  'F8:1A:67': { vendor: 'TP-Link', type: 'Consumer Network' },
  '90:F6:52': { vendor: 'TP-Link', type: 'Consumer Network' },
  '00:27:19': { vendor: 'TP-Link', type: 'Consumer Network' },
  '14:CC:20': { vendor: 'TP-Link', type: 'Consumer Network' },
  '30:B5:C2': { vendor: 'TP-Link', type: 'Consumer Network' },
  '50:FA:84': { vendor: 'TP-Link', type: 'Consumer Network' },
  '64:70:02': { vendor: 'TP-Link', type: 'Consumer Network' },
  '78:A1:06': { vendor: 'TP-Link', type: 'Consumer Network' },
  '94:0C:6D': { vendor: 'TP-Link', type: 'Consumer Network' },
  'A0:F3:C1': { vendor: 'TP-Link', type: 'Consumer Network' },
  'B0:95:8E': { vendor: 'TP-Link', type: 'Consumer Network' },
  'C0:25:E9': { vendor: 'TP-Link', type: 'Consumer Network' },
  'C4:6E:1F': { vendor: 'TP-Link', type: 'Consumer Network' },
  'D8:07:B6': { vendor: 'TP-Link', type: 'Consumer Network' },
  'E8:DE:27': { vendor: 'TP-Link', type: 'Consumer Network' },
  'EC:08:6B': { vendor: 'TP-Link', type: 'Consumer Network' },
  'EC:17:2F': { vendor: 'TP-Link', type: 'Consumer Network' },
  '00:0F:66': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:06:25': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:0E:08': { vendor: 'Linksys', type: 'Consumer Network' },
  '20:AA:4B': { vendor: 'Linksys', type: 'Consumer Network' },
  '00:1F:E2': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '00:24:54': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '00:26:5D': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '10:D5:42': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '30:CD:A7': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '5C:0A:5B': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '60:A1:0A': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '6C:F3:73': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '7C:0B:C6': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '80:65:6D': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '90:18:7C': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'A8:06:00': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'AC:5F:3E': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'B4:79:A7': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'BC:85:1F': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'C4:42:02': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'CC:07:AB': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'D0:22:BE': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'E4:7C:F9': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'EC:1F:72': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'F4:09:D8': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  'FC:A1:3E': { vendor: 'Samsung Electronics', type: 'Consumer Electronics' },
  '00:18:E7': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '00:FC:8B': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '0C:47:C9': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '10:AE:60': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '18:74:2E': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '24:4C:E3': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '34:D2:70': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '38:F7:3D': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '40:B4:CD': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '44:65:0D': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '50:DC:E7': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '5C:41:5A': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '68:37:E9': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '68:54:FD': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '74:75:48': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '78:E1:03': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '84:D6:D0': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '8C:49:62': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'A0:02:DC': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'AC:63:BE': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'B4:7C:9C': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'CC:9E:A2': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'F0:27:2D': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'F0:D2:F1': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  'FC:A6:67': { vendor: 'Amazon Technologies', type: 'Consumer Electronics' },
  '00:1E:58': { vendor: 'D-Link', type: 'Consumer Network' },
  '00:22:B0': { vendor: 'D-Link', type: 'Consumer Network' },
  '00:24:01': { vendor: 'D-Link', type: 'Consumer Network' },
  '00:26:5A': { vendor: 'D-Link', type: 'Consumer Network' },
  '14:D6:4D': { vendor: 'D-Link', type: 'Consumer Network' },
  '1C:7E:E5': { vendor: 'D-Link', type: 'Consumer Network' },
  '28:10:7B': { vendor: 'D-Link', type: 'Consumer Network' },
  '34:08:04': { vendor: 'D-Link', type: 'Consumer Network' },
  '78:32:1B': { vendor: 'D-Link', type: 'Consumer Network' },
  '84:C9:B2': { vendor: 'D-Link', type: 'Consumer Network' },
  '90:94:E4': { vendor: 'D-Link', type: 'Consumer Network' },
  '9C:D6:43': { vendor: 'D-Link', type: 'Consumer Network' },
  'B8:A3:86': { vendor: 'D-Link', type: 'Consumer Network' },
  'C8:BE:19': { vendor: 'D-Link', type: 'Consumer Network' },
  'CC:B2:55': { vendor: 'D-Link', type: 'Consumer Network' },
  'F0:B4:29': { vendor: 'D-Link', type: 'Consumer Network' },
  '00:04:0E': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '00:1C:4A': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '24:65:11': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '34:31:C4': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '5C:49:79': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '88:71:B1': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  '9C:C7:D1': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  'B0:75:0C': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  'C0:25:06': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  'C8:0E:14': { vendor: 'AVM GmbH (FRITZ!Box)', type: 'Consumer Network' },
  'D8:5D:4C': { vendor: 'TP-Link', type: 'Consumer Network' },
  'E8:94:F6': { vendor: 'TP-Link', type: 'Consumer Network' },
  'F4:F2:6D': { vendor: 'TP-Link', type: 'Consumer Network' },
  'F8:D1:11': { vendor: 'TP-Link', type: 'Consumer Network' },
  '00:E0:4C': { vendor: 'Realtek Semiconductor', type: 'Network Interface' },
  '52:54:00': { vendor: 'QEMU/KVM', type: 'Virtualization' },
  'FE:FF:FF': { vendor: 'Broadcast/Multicast', type: 'Special' },
  'FF:FF:FF': { vendor: 'Broadcast', type: 'Special' },
  '01:00:5E': { vendor: 'IPv4 Multicast', type: 'Special' },
  '33:33:00': { vendor: 'IPv6 Multicast', type: 'Special' },
  '00:1E:C2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:23:32': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:1F:5B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:25:00': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:25:BC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:26:4A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '04:0C:CE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '0C:3E:9F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '10:40:F3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '10:93:E9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '10:DD:B1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '14:10:9F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '18:AF:8F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '1C:AB:A7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '20:78:F0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '20:A2:E4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '20:C9:D0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '24:A0:74': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:0B:5C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:37:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:5A:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:6A:B8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:CF:DA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:E0:2C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:E1:4C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:ED:6A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '28:F0:76': { vendor: 'Apple', type: 'Consumer Electronics' },
  '2C:1F:23': { vendor: 'Apple', type: 'Consumer Electronics' },
  '2C:3F:38': { vendor: 'Apple', type: 'Consumer Electronics' },
  '2C:BE:08': { vendor: 'Apple', type: 'Consumer Electronics' },
  '2C:F0:A2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '30:10:E4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '30:35:AD': { vendor: 'Apple', type: 'Consumer Electronics' },
  '30:90:AB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '30:F7:C5': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:08:BC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:12:98': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:15:9E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:36:3B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:51:C9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:A3:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:AB:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:C0:59': { vendor: 'Apple', type: 'Consumer Electronics' },
  '34:E2:FD': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:0F:4A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:4F:F0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:66:F0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:71:DE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:B5:4D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:C9:86': { vendor: 'Apple', type: 'Consumer Electronics' },
  '38:CA:DA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '3C:07:54': { vendor: 'Apple', type: 'Consumer Electronics' },
  '3C:15:C2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '3C:2E:F9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '3C:D0:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '3C:E0:72': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:30:04': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:33:1A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:3C:FC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:4D:7F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:6C:8F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:83:1D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:98:AD': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:9C:28': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:A6:D9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:B3:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:BC:60': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:C4:FF': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:CB:C0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '40:D3:2D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '44:00:10': { vendor: 'Apple', type: 'Consumer Electronics' },
  '44:2A:60': { vendor: 'Apple', type: 'Consumer Electronics' },
  '44:D8:84': { vendor: 'Apple', type: 'Consumer Electronics' },
  '44:FB:42': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:43:7C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:4B:AA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:60:BC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:74:6E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:A1:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:BF:6B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:D7:05': { vendor: 'Apple', type: 'Consumer Electronics' },
  '48:E9:F1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:32:75': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:57:CA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:74:03': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:7C:5F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:8D:79': { vendor: 'Apple', type: 'Consumer Electronics' },
  '4C:B1:99': { vendor: 'Apple', type: 'Consumer Electronics' },
  '50:32:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  '50:7A:55': { vendor: 'Apple', type: 'Consumer Electronics' },
  '50:82:D5': { vendor: 'Apple', type: 'Consumer Electronics' },
  '50:BC:96': { vendor: 'Apple', type: 'Consumer Electronics' },
  '50:EA:D6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:4E:90': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:72:4F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:99:63': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:9F:13': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:AE:27': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:E4:3A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:EA:A8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '54:EE:75': { vendor: 'Apple', type: 'Consumer Electronics' },
  '58:1F:AA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '58:40:4E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '58:55:CA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '58:7F:57': { vendor: 'Apple', type: 'Consumer Electronics' },
  '58:B0:35': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:59:48': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:8D:4E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:95:AE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:96:9D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:97:F3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '5C:F7:E6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:03:08': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:30:D4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:33:4B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:69:44': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:92:17': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:C5:47': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:D9:C7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:F4:45': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:FA:CD': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:FB:42': { vendor: 'Apple', type: 'Consumer Electronics' },
  '60:FE:C5': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:20:0C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:4B:F0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:76:BA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:9A:BE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:A3:CB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:A5:C3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:B0:A6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:B9:E8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '64:E6:82': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:09:27': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:5B:35': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:64:4B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:96:7B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:9C:70': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:A8:6D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:AB:1E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:AE:20': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:D9:3C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:DB:CA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:FB:7E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '68:FE:F7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:19:C0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:3E:6D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:40:08': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:4D:73': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:70:9F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:72:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:8D:C1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:94:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:96:CF': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:AB:31': { vendor: 'Apple', type: 'Consumer Electronics' },
  '6C:C2:6B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:11:24': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:3E:AC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:48:0F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:56:81': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:73:CB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:81:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:A2:B3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:CD:60': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:DE:E2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:EC:E4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '70:F0:87': { vendor: 'Apple', type: 'Consumer Electronics' },
  '74:1B:B2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '74:8D:08': { vendor: 'Apple', type: 'Consumer Electronics' },
  '74:9E:AF': { vendor: 'Apple', type: 'Consumer Electronics' },
  '74:E1:B6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '74:E2:F5': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:31:C1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:3A:84': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:4F:43': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:67:D7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:6C:1C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:7B:8A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:7E:61': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:88:6D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:9F:70': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:A3:E4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:CA:39': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:D7:5F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '78:FD:94': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:01:91': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:04:D0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:11:BE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:5C:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:6D:62': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:6D:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:9A:1D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:B7:33': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:C3:A1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:C5:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:D1:C3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:E9:D3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:F0:5F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '7C:FA:DF': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:00:6E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:49:71': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:82:23': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:92:9F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:E6:50': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:EA:96': { vendor: 'Apple', type: 'Consumer Electronics' },
  '80:ED:2C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:29:99': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:38:35': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:78:8B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:85:06': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:89:AD': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:8E:0C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:A1:34': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:B1:53': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:FC:AC': { vendor: 'Apple', type: 'Consumer Electronics' },
  '84:FC:FE': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:1F:A1': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:53:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:63:DF': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:66:A5': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:6B:6E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:C6:63': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:CB:87': { vendor: 'Apple', type: 'Consumer Electronics' },
  '88:E8:7F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:00:6D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:29:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:2D:AA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:58:77': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:7B:9D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:7C:92': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:85:90': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:8E:F2': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:8F:E9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '8C:FA:BA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:27:E4': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:3C:92': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:72:40': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:8D:6C': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:9C:4A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:B0:ED': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:B2:1F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:B9:31': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:C1:C6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:DD:5D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '90:FD:61': { vendor: 'Apple', type: 'Consumer Electronics' },
  '94:94:26': { vendor: 'Apple', type: 'Consumer Electronics' },
  '94:BF:2D': { vendor: 'Apple', type: 'Consumer Electronics' },
  '94:E9:6A': { vendor: 'Apple', type: 'Consumer Electronics' },
  '94:F6:A3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:00:C6': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:01:A7': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:03:D8': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:5A:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:9E:63': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:B8:E3': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:CA:33': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:D6:BB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:E0:D9': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:F0:AB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '98:FE:94': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:04:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:20:7B': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:29:3F': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:35:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:4F:DA': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:8B:A0': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:F4:8E': { vendor: 'Apple', type: 'Consumer Electronics' },
  '9C:FC:01': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:18:28': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:3B:E3': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:4E:A7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:56:F3': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:78:BA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:99:9B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:D7:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A0:ED:CD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:31:35': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:5E:60': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:67:06': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:83:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:B1:97': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:B8:05': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:C3:61': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:D1:8C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:D1:D2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:E9:75': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A4:F1:E8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:20:66': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:51:5B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:5B:78': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:66:7F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:88:08': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:8E:24': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:96:8A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:BB:CF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:BE:27': { vendor: 'Apple', type: 'Consumer Electronics' },
  'A8:FA:D8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:29:3A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:3C:0B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:61:EA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:7F:3E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:87:A3': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:BC:32': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:CF:5C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:E4:B5': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:EE:9E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'AC:FD:EC': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:19:C6': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:34:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:48:1A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:65:BD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:70:2D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B0:9F:BA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:18:D1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:4B:D2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:8B:19': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:9C:DF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:F0:AB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B4:F1:DA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:09:8A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:17:C2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:41:A4': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:44:D9': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:53:AC': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:5A:F7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:63:4D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:78:2E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:8D:12': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:C1:11': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:C7:5D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:E8:56': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:F6:B1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'B8:FF:61': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:3B:AF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:4C:C4': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:52:B7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:54:36': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:67:1C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:6C:21': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:79:AD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:92:6B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:A9:20': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:EC:5D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'BC:FE:D9': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:1A:DA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:63:94': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:84:7A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:9F:42': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:A5:3E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:B6:58': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:CC:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:CE:CD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:D0:12': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:D3:C0': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C0:F2:FB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C4:2C:03': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C4:B3:01': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:1E:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:2A:14': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:33:4B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:3C:85': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:69:CD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:6F:1D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:85:50': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:B5:B7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:BC:C8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:D0:83': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:E0:EB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'C8:F6:50': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:08:8D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:20:E8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:25:EF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:29:F5': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:44:63': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:78:5F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'CC:C7:60': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:03:4B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:23:DB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:25:98': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:33:11': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:4F:7E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:A6:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:C5:F3': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:D2:B0': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D0:E1:40': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D4:61:9D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D4:9A:20': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D4:DC:CD': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D4:F4:6F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:00:4D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:1D:72': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:30:62': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:8F:76': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:96:95': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:9E:3F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:A2:5E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:BB:2C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:CF:9C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'D8:D1:CB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:08:56': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:0C:5C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:2B:2A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:2B:61': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:37:14': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:41:5F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:56:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:86:D8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:9B:9C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:A4:CA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:A9:04': { vendor: 'Apple', type: 'Consumer Electronics' },
  'DC:D3:A2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:5F:45': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:66:78': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:AC:CB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:B5:2D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:B9:BA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:C7:67': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:C9:7A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:F5:C6': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E0:F8:47': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:25:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:2B:34': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:98:D6': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:9A:DC': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:C6:3D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:CE:8F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:E0:A6': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E4:E4:AB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E8:04:0B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E8:06:88': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E8:80:2E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E8:8D:28': { vendor: 'Apple', type: 'Consumer Electronics' },
  'E8:B2:AC': { vendor: 'Apple', type: 'Consumer Electronics' },
  'EC:35:86': { vendor: 'Apple', type: 'Consumer Electronics' },
  'EC:85:2F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'EC:AD:B8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:18:98': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:24:75': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:4F:7C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:5B:7B': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:79:59': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:7B:CB': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:98:9D': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:99:BF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:B0:E7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:B4:79': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:C1:F1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:CB:A1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:D1:A9': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:DB:E2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:DB:F8': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:DC:E2': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F0:F6:1C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:1B:A1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:31:C3': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:37:B7': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:5C:89': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:5C:8A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:BD:9E': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:C2:48': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:D4:88': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:F1:5A': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F4:F9:51': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:03:32': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:10:37': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:1E:DF': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:27:93': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:38:80': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:4D:89': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:62:14': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:6F:C1': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:95:EA': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:E0:79': { vendor: 'Apple', type: 'Consumer Electronics' },
  'F8:E9:03': { vendor: 'Apple', type: 'Consumer Electronics' },
  'FC:25:3F': { vendor: 'Apple', type: 'Consumer Electronics' },
  'FC:2A:9C': { vendor: 'Apple', type: 'Consumer Electronics' },
  'FC:D8:48': { vendor: 'Apple', type: 'Consumer Electronics' },
  'FC:E9:98': { vendor: 'Apple', type: 'Consumer Electronics' },
  '00:1B:77': { vendor: 'Intel', type: 'Network Interface' },
  '00:1C:C0': { vendor: 'Intel', type: 'Network Interface' },
  '00:1D:E0': { vendor: 'Intel', type: 'Network Interface' },
  '00:1E:64': { vendor: 'Intel', type: 'Network Interface' },
  '00:1E:65': { vendor: 'Intel', type: 'Network Interface' },
  '00:1F:3B': { vendor: 'Intel', type: 'Network Interface' },
  '00:1F:3C': { vendor: 'Intel', type: 'Network Interface' },
  '00:20:E0': { vendor: 'Intel', type: 'Network Interface' },
  '00:21:5C': { vendor: 'Intel', type: 'Network Interface' },
  '00:21:5D': { vendor: 'Intel', type: 'Network Interface' },
  '00:21:6A': { vendor: 'Intel', type: 'Network Interface' },
  '00:21:6B': { vendor: 'Intel', type: 'Network Interface' },
  '00:22:FA': { vendor: 'Intel', type: 'Network Interface' },
  '00:22:FB': { vendor: 'Intel', type: 'Network Interface' },
  '00:23:14': { vendor: 'Intel', type: 'Network Interface' },
  '00:23:15': { vendor: 'Intel', type: 'Network Interface' },
  '00:24:7B': { vendor: 'Intel', type: 'Network Interface' },
  '00:24:D7': { vendor: 'Intel', type: 'Network Interface' },
  '00:26:C6': { vendor: 'Intel', type: 'Network Interface' },
  '00:26:C7': { vendor: 'Intel', type: 'Network Interface' },
  '00:27:10': { vendor: 'Intel', type: 'Network Interface' },
  '00:AA:01': { vendor: 'Intel', type: 'Network Interface' },
  '00:AA:02': { vendor: 'Intel', type: 'Network Interface' },
  '0C:8B:FD': { vendor: 'Intel', type: 'Network Interface' },
  '0C:D2:92': { vendor: 'Intel', type: 'Network Interface' },
  '10:02:B5': { vendor: 'Intel', type: 'Network Interface' },
  '10:4A:7D': { vendor: 'Intel', type: 'Network Interface' },
  '18:1D:EA': { vendor: 'Intel', type: 'Network Interface' },
  '18:3D:A2': { vendor: 'Intel', type: 'Network Interface' },
  '18:DB:F2': { vendor: 'Intel', type: 'Network Interface' },
  '1C:1B:0D': { vendor: 'Intel', type: 'Network Interface' },
  '1C:69:7A': { vendor: 'Intel', type: 'Network Interface' },
  '24:77:03': { vendor: 'Intel', type: 'Network Interface' },
  '28:B2:BD': { vendor: 'Intel', type: 'Network Interface' },
  '2C:D0:5A': { vendor: 'Intel', type: 'Network Interface' },
  '34:02:86': { vendor: 'Intel', type: 'Network Interface' },
  '34:13:E8': { vendor: 'Intel', type: 'Network Interface' },
  '34:E6:AD': { vendor: 'Intel', type: 'Network Interface' },
  '34:F3:9A': { vendor: 'Intel', type: 'Network Interface' },
  '38:BA:F8': { vendor: 'Intel', type: 'Network Interface' },
  '38:DE:AD': { vendor: 'Intel', type: 'Network Interface' },
  '3C:15:FB': { vendor: 'Intel', type: 'Network Interface' },
  '3C:58:C2': { vendor: 'Intel', type: 'Network Interface' },
  '3C:6A:A7': { vendor: 'Intel', type: 'Network Interface' },
  '3C:A9:F4': { vendor: 'Intel', type: 'Network Interface' },
  '40:25:C2': { vendor: 'Intel', type: 'Network Interface' },
  '40:74:E0': { vendor: 'Intel', type: 'Network Interface' },
  '40:D8:55': { vendor: 'Intel', type: 'Network Interface' },
  '44:85:00': { vendor: 'Intel', type: 'Network Interface' },
  '48:21:0B': { vendor: 'Intel', type: 'Network Interface' },
  '48:45:20': { vendor: 'Intel', type: 'Network Interface' },
  '48:51:B7': { vendor: 'Intel', type: 'Network Interface' },
  '48:53:00': { vendor: 'Intel', type: 'Network Interface' },
  '4C:34:88': { vendor: 'Intel', type: 'Network Interface' },
  '4C:79:6E': { vendor: 'Intel', type: 'Network Interface' },
  '50:76:AF': { vendor: 'Intel', type: 'Network Interface' },
  '50:E0:85': { vendor: 'Intel', type: 'Network Interface' },
  '50:EB:71': { vendor: 'Intel', type: 'Network Interface' },
  '54:8D:5A': { vendor: 'Intel', type: 'Network Interface' },
  '58:91:CF': { vendor: 'Intel', type: 'Network Interface' },
  '58:94:6B': { vendor: 'Intel', type: 'Network Interface' },
  '58:A8:39': { vendor: 'Intel', type: 'Network Interface' },
  '5C:51:4F': { vendor: 'Intel', type: 'Network Interface' },
  '5C:87:9C': { vendor: 'Intel', type: 'Network Interface' },
  '5C:C5:D4': { vendor: 'Intel', type: 'Network Interface' },
  '5C:E0:C5': { vendor: 'Intel', type: 'Network Interface' },
  '60:57:18': { vendor: 'Intel', type: 'Network Interface' },
  '60:6C:66': { vendor: 'Intel', type: 'Network Interface' },
  '60:F6:77': { vendor: 'Intel', type: 'Network Interface' },
  '64:51:06': { vendor: 'Intel', type: 'Network Interface' },
  '64:D4:DA': { vendor: 'Intel', type: 'Network Interface' },
  '68:05:CA': { vendor: 'Intel', type: 'Network Interface' },
  '68:17:29': { vendor: 'Intel', type: 'Network Interface' },
  '68:1D:EF': { vendor: 'Intel', type: 'Network Interface' },
  '6C:29:95': { vendor: 'Intel', type: 'Network Interface' },
  '6C:88:14': { vendor: 'Intel', type: 'Network Interface' },
  '70:1C:E7': { vendor: 'Intel', type: 'Network Interface' },
  '70:5A:0F': { vendor: 'Intel', type: 'Network Interface' },
  '78:0C:B8': { vendor: 'Intel', type: 'Network Interface' },
  '78:28:CA': { vendor: 'Intel', type: 'Network Interface' },
  '78:2B:CB': { vendor: 'Intel', type: 'Network Interface' },
  '78:92:9C': { vendor: 'Intel', type: 'Network Interface' },
  '78:FF:57': { vendor: 'Intel', type: 'Network Interface' },
  '7C:7A:91': { vendor: 'Intel', type: 'Network Interface' },
  '80:19:34': { vendor: 'Intel', type: 'Network Interface' },
  '80:56:F2': { vendor: 'Intel', type: 'Network Interface' },
  '80:86:F2': { vendor: 'Intel', type: 'Network Interface' },
  '80:9B:20': { vendor: 'Intel', type: 'Network Interface' },
  '80:C5:F2': { vendor: 'Intel', type: 'Network Interface' },
  '84:3A:4B': { vendor: 'Intel', type: 'Network Interface' },
  '84:A6:C8': { vendor: 'Intel', type: 'Network Interface' },
  '84:EF:18': { vendor: 'Intel', type: 'Network Interface' },
  '88:78:73': { vendor: 'Intel', type: 'Network Interface' },
  '88:B1:11': { vendor: 'Intel', type: 'Network Interface' },
  '8C:8D:28': { vendor: 'Intel', type: 'Network Interface' },
  '8C:94:1F': { vendor: 'Intel', type: 'Network Interface' },
  '90:2E:1C': { vendor: 'Intel', type: 'Network Interface' },
  '90:48:9A': { vendor: 'Intel', type: 'Network Interface' },
  '90:61:AE': { vendor: 'Intel', type: 'Network Interface' },
  '90:E2:BA': { vendor: 'Intel', type: 'Network Interface' },
  '94:65:9C': { vendor: 'Intel', type: 'Network Interface' },
  '98:4F:EE': { vendor: 'Intel', type: 'Network Interface' },
  '9C:2A:70': { vendor: 'Intel', type: 'Network Interface' },
  '9C:4E:36': { vendor: 'Intel', type: 'Network Interface' },
  'A0:36:9F': { vendor: 'Intel', type: 'Network Interface' },
  'A0:51:0B': { vendor: 'Intel', type: 'Network Interface' },
  'A0:A8:CD': { vendor: 'Intel', type: 'Network Interface' },
  'A0:C5:89': { vendor: 'Intel', type: 'Network Interface' },
  'A4:02:B9': { vendor: 'Intel', type: 'Network Interface' },
  'A4:34:D9': { vendor: 'Intel', type: 'Network Interface' },
  'A4:4C:C8': { vendor: 'Intel', type: 'Network Interface' },
  'A4:C4:94': { vendor: 'Intel', type: 'Network Interface' },
  'AC:72:89': { vendor: 'Intel', type: 'Network Interface' },
  'AC:7B:A1': { vendor: 'Intel', type: 'Network Interface' },
  'AC:FD:CE': { vendor: 'Intel', type: 'Network Interface' },
  'B0:35:9F': { vendor: 'Intel', type: 'Network Interface' },
  'B4:6B:FC': { vendor: 'Intel', type: 'Network Interface' },
  'B4:6D:83': { vendor: 'Intel', type: 'Network Interface' },
  'B4:96:91': { vendor: 'Intel', type: 'Network Interface' },
  'B4:AE:2B': { vendor: 'Intel', type: 'Network Interface' },
  'B4:D5:BD': { vendor: 'Intel', type: 'Network Interface' },
  'B4:E1:C4': { vendor: 'Intel', type: 'Network Interface' },
  'B8:03:05': { vendor: 'Intel', type: 'Network Interface' },
  'B8:08:CF': { vendor: 'Intel', type: 'Network Interface' },
  'B8:9A:2A': { vendor: 'Intel', type: 'Network Interface' },
  'BC:0F:64': { vendor: 'Intel', type: 'Network Interface' },
  'BC:77:37': { vendor: 'Intel', type: 'Network Interface' },
  'BC:A8:A6': { vendor: 'Intel', type: 'Network Interface' },
  'C4:17:FE': { vendor: 'Intel', type: 'Network Interface' },
  'C4:85:08': { vendor: 'Intel', type: 'Network Interface' },
  'C4:D9:87': { vendor: 'Intel', type: 'Network Interface' },
  'C8:5B:76': { vendor: 'Intel', type: 'Network Interface' },
  'C8:B2:9B': { vendor: 'Intel', type: 'Network Interface' },
  'CC:2F:71': { vendor: 'Intel', type: 'Network Interface' },
  'D0:22:12': { vendor: 'Intel', type: 'Network Interface' },
  'D0:AB:D5': { vendor: 'Intel', type: 'Network Interface' },
  'D4:3B:04': { vendor: 'Intel', type: 'Network Interface' },
  'D8:5D:E2': { vendor: 'Intel', type: 'Network Interface' },
  'D8:FC:93': { vendor: 'Intel', type: 'Network Interface' },
  'DC:53:60': { vendor: 'Intel', type: 'Network Interface' },
  'E0:94:67': { vendor: 'Intel', type: 'Network Interface' },
  'E0:9D:31': { vendor: 'Intel', type: 'Network Interface' },
  'E4:B3:18': { vendor: 'Intel', type: 'Network Interface' },
  'E8:B1:FC': { vendor: 'Intel', type: 'Network Interface' },
  'EC:0E:C4': { vendor: 'Intel', type: 'Network Interface' },
  'F0:1F:AF': { vendor: 'Intel', type: 'Network Interface' },
  'F4:06:69': { vendor: 'Intel', type: 'Network Interface' },
  'F4:8C:50': { vendor: 'Intel', type: 'Network Interface' },
  'F8:16:54': { vendor: 'Intel', type: 'Network Interface' },
  'F8:63:3F': { vendor: 'Intel', type: 'Network Interface' },
  'F8:94:C2': { vendor: 'Intel', type: 'Network Interface' },
  'FC:F8:AE': { vendor: 'Intel', type: 'Network Interface' },
  '00:30:A3': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '0C:8D:DB': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '34:56:FE': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  'AC:17:02': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  'AC:22:05': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  'E0:55:3D': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  'E0:CB:BC': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  'AC:67:06': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '00:18:0A': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '00:18:74': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '68:3A:48': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
  '88:15:44': { vendor: 'Cisco Meraki', type: 'Network Equipment' },
};

export default function MACLookup() {
  const [isDark, setIsDark] = useState(true);
  const [macInput, setMacInput] = useState('');
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    setIsDark(document.documentElement.classList.contains('dark'));
  }, []);

  const normalizeMac = (mac) => {
    // Remove all separators and convert to uppercase
    const cleaned = mac.replace(/[:\-\.]/g, '').toUpperCase();
    if (cleaned.length < 6) return null;
    // Format as XX:XX:XX
    return cleaned.substring(0, 6).match(/.{2}/g).join(':');
  };

  const formatMac = (mac) => {
    const cleaned = mac.replace(/[:\-\.]/g, '').toUpperCase();
    if (cleaned.length !== 12) return mac;
    return cleaned.match(/.{2}/g).join(':');
  };

  const lookupMac = () => {
    setError('');
    setResult(null);

    if (!macInput.trim()) {
      setError('Please enter a MAC address');
      return;
    }

    const oui = normalizeMac(macInput);
    if (!oui) {
      setError('Invalid MAC address format');
      return;
    }

    const vendor = ouiDatabase[oui];
    if (vendor) {
      setResult({
        mac: formatMac(macInput),
        oui,
        ...vendor
      });
    } else {
      setResult({
        mac: formatMac(macInput),
        oui,
        vendor: 'Unknown',
        type: 'Not in database'
      });
    }
  };

  const getTypeBadge = (type) => {
    const styles = {
      'Network Equipment': 'bg-blue-500/20 text-blue-400 border-blue-500/30',
      'Consumer Network': 'bg-green-500/20 text-green-400 border-green-500/30',
      'Consumer Electronics': 'bg-purple-500/20 text-purple-400 border-purple-500/30',
      'Computer': 'bg-amber-500/20 text-amber-400 border-amber-500/30',
      'Server': 'bg-red-500/20 text-red-400 border-red-500/30',
      'Virtualization': 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
      'Network Interface': 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30',
      'Special': 'bg-pink-500/20 text-pink-400 border-pink-500/30',
    };
    return styles[type] || 'bg-slate-500/20 text-slate-400 border-slate-500/30';
  };

  return (
    <ToolPageWrapper
      title="MAC/OUI Lookup"
      description="Identify device manufacturers from MAC addresses"
      icon={Database}
      tips={[
        'Enter a MAC address to identify the manufacturer.',
        'Supports formats: XX:XX:XX:XX:XX:XX, XX-XX-XX-XX-XX-XX, or XXXXXXXXXXXX'
      ]}
    >
      <div className="space-y-6">
        {/* Input Section */}
        <div className="grid gap-4 md:grid-cols-3">
          <div className="md:col-span-2">
            <Label>MAC Address</Label>
            <Input
              value={macInput}
              onChange={(e) => setMacInput(e.target.value)}
              placeholder="00:1A:2B:3C:4D:5E"
              className={`mt-1 font-mono ${isDark ? 'bg-slate-800 border-slate-700' : ''}`}
              onKeyDown={(e) => e.key === 'Enter' && lookupMac()}
            />
          </div>
          <div className="flex items-end">
            <Button 
              onClick={lookupMac}
              className="w-full bg-gradient-to-r from-cyan-500 to-blue-600"
            >
              <Search className="h-4 w-4 mr-2" />
              Lookup
            </Button>
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className={`p-4 rounded-xl ${isDark ? 'bg-red-500/10 border border-red-500/20' : 'bg-red-50 border border-red-100'}`}>
            <p className="text-red-400">{error}</p>
          </div>
        )}

        {/* Result */}
        {result && (
          <div className={`p-6 rounded-xl space-y-4 ${isDark ? 'bg-slate-800/50' : 'bg-slate-50'}`}>
            <div className="grid gap-4 md:grid-cols-2">
              <ResultCard label="MAC Address" value={result.mac} />
              <ResultCard label="OUI (First 3 bytes)" value={result.oui} />
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className={`p-4 rounded-xl ${isDark ? 'bg-slate-900/50' : 'bg-white'}`}>
                <p className={`text-xs font-medium uppercase tracking-wider mb-2 ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>
                  Vendor / Manufacturer
                </p>
                <p className={`text-xl font-semibold ${result.vendor === 'Unknown' ? 'text-slate-500' : ''}`}>
                  {result.vendor}
                </p>
              </div>
              <div className={`p-4 rounded-xl ${isDark ? 'bg-slate-900/50' : 'bg-white'}`}>
                <p className={`text-xs font-medium uppercase tracking-wider mb-2 ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>
                  Device Type
                </p>
                <Badge className={`${getTypeBadge(result.type)} border text-sm`}>
                  {result.type}
                </Badge>
              </div>
            </div>
          </div>
        )}

        {/* Info about OUI */}
        <div className={`p-6 rounded-xl ${isDark ? 'bg-slate-800/50' : 'bg-slate-50'}`}>
          <div className="flex items-start gap-3 mb-4">
            <Info className="h-5 w-5 text-cyan-500 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold mb-2">About OUI (Organizationally Unique Identifier)</h3>
              <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                The first 3 bytes (6 hex digits) of a MAC address identify the manufacturer. This is called the OUI 
                and is assigned by the IEEE. The remaining 3 bytes are assigned by the manufacturer to uniquely 
                identify each device.
              </p>
            </div>
          </div>
          <div className="grid gap-4 md:grid-cols-3 mt-4">
            <div className={`p-3 rounded-lg ${isDark ? 'bg-slate-900/50' : 'bg-white'}`}>
              <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Database Entries</p>
              <p className="text-2xl font-bold text-cyan-400">{Object.keys(ouiDatabase).length}</p>
            </div>
            <div className={`p-3 rounded-lg ${isDark ? 'bg-slate-900/50' : 'bg-white'}`}>
              <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Lookup Type</p>
              <p className="text-lg font-medium">Offline</p>
            </div>
            <div className={`p-3 rounded-lg ${isDark ? 'bg-slate-900/50' : 'bg-white'}`}>
              <p className={`text-sm ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Privacy</p>
              <p className="text-lg font-medium">100% Local</p>
            </div>
          </div>
        </div>
      </div>
    </ToolPageWrapper>
  );
}